export const SET_SYMBOL = "SET_SYMBOL";
export const SET_CURRENCY = "SET_CURRENCY";
export const SET_LOCAL = "SET_LOCAL";
export const SET_COINS = "SET_COINS";
export const SET_LOADING = "SET_LOADING";
export const SET_USER = "SET_USER";
export const SET_WATCHLIST = "SET_WATCHLIST";
export const SET_ALERT = "SET_ALERT";
export const SET_SEARCH_KEYWORD = "SET_SEARCH_KEYWORD ";
